sudo: required
dist: trusty
language: generic
script: make && make test
after_success:
- make deploy
deploy:
- provider: releases
  api_key:
    secure: Eb+0GC0pGWQ4JfyMhJauLaoZ8Lycr9p95eRF9/JcBAXPn6Eo69JV+ybakRzKm1sGV9QpA+OzMFfNgRsY1zqGhgk8kBbAqT+Q+BxZDw+UGKKxA4Mgwv4Y/8O72pxcZqaIPkS8desYC0Z6bG1JYKdBIpIFZk9le9w7wIOt11xFmIljHWVe0qP4O6ksJSrhdOGxr1RTlty5Okhb8aqVgIQE7mc56npSl2CqRX7PmpADSLszSNZnXYIkTytY4n+70Nax9wPb/5xPULCwtSdJWFUxjah2aHa/W51mzT/KtHZvcfiKU4jmeybsijMRi3wrVOm1P/qbKE6XQPSLAEh+JFPdMfhG4qxObhbLTyHHJ9TDdT1ELf1g74dY+2VH+ZYm3wH0TLYNOTn/qql3y/798/+ZvhhavPvtx19gkk/HwHBgzp2PV3vfp0iQeScIszby0cXZzrieBypNERZrRI7VwTAng2gSYCrJUSDGm5IFablbRnxYz+w4Bw5DcbTYu3Z8+4cX1r57SLehRDDs7V/nu+f8l/3aSUEJgzCjLO2CxepEJBDr2gJTio43mjHjuXLp+mG3+TaSbP6RTkI72bOElaIjGw+jwceCy/A9vKlUc2gW7sH5+KuJzXfwscD5gLbTTCEHMpd3XcaofMm5Hh9fK2ntPvMd3+kcvfPvwSiQOT/8kkI=
  file:
  - dist/dit4c-helper-upload-webdav.linux.amd64.aci
  - dist/SHA512SUM
  skip_cleanup: true
  on:
    tags: true
    repo: dit4c/dit4c-helper-upload-webdav
- provider: bintray
  file: dist/bintray-descriptor.json
  user: tjdett
  passphrase:
    secure: EpH3EaRNavMiiM/f/sm8qLPalJy53bXHn0yQjvI5sCY6a7TTW0XFWg9HY2zb43ilNC6j7ULhcANiHfrTj+Ok7E9lsJWVM2x8zbgOg/nLqj8juoXyUpwpxrvkLer4qhx94nfcLuIMY5vwbhfeVYH16J9/gxK++vC/ze4EZGoXgdWVlQnPaQi/QVeqx6Kk9U99Jqr4rnWOeCJ8zCpOBX+HaTbgzLpsl2YALU7fA82yU2XNt0+XIkbiLT8OY46mB33aW9Fit/oBmyuhkMRG/3DTstmt4Mx6Ei+vSlSGFZhy1PUviYHETh1yJs6jg9/ZPgYI8KRlKxggTq4ymt0ZFcRzYGI++WJ6mSQjZ6YtMBeTTNAjbrClopuotYxZDqhPHVOHlTXsTpW8x8OxVtEJ/fZtke4MUj7MMWOv8wGKzvGvtzxlsy6u+riZPpnguKriklMgbbgKnYDtcWGB0owLoTAwi75V4q3cBl7ppSIDiIxdNpR/KV6uGwu1tIUXvew/5omUE495eTylnxDGjiOH24bRhlSLQjOk+84AAvdx1mTKr3oH7IHs7tx2iKcJAYrLippdfHKmqJLPUqicVRirWthAVqpuM2y0uAjcJUJbAOQ8h3p0/88i+onLswcTX93SNpTUd98mspr/1gedL4/Lt9nh0Xi/Uhs9UmHuKzQT9b7Ttho=
  key:
    secure: IoL71WnPnMUmgjWOfwM42cbdCFrDwvgALCXF7w9515rCr7PMT57vXkesxCDbLJZ5LRQuELMJX/w4xvT2SbhbLQ8QOYxASkv1J/xbSJid8bg8VhGowQdOZP8I444WdLuoJgnd87gJSPnMvfkRNrhJjWMXA/aEKFhCEFnwV9MyUX8l6qeprW4BRCcz4qFM9uwWCKMDPzi/t5fGm9PdClc3jupb5seF4E0ldJiXif80WyQgjatA39UjPYDITRb0mylpCBHFtxhiLZSFtosDK68/ekgidiHrj73S3ciils8bQDjaNRSKkK9UYD9cTA/osZqO5t8/m3LbGHusKjCbil5DfwawiMivGeZGiyO7ID82u2BHuLxBaW8V9nQ9SlGY7oYR12hMTY9NY2NssFWtLPX9ctkkeCtaR46TrTbYOG9d5+5FuOqpedNNLcWyAu+389L6flRs07319gw9ku7dyTv9DxNWBINAEs+njrxbfY4jnXCoFWChOlM0ed4PPL/my4CMO0bkmLR6s4cWzWuDATRUjd40ICwH3n0LN0SrpbB1hCt/TBjcm9LnbVWbhVTCj3x3pyzIB0o0GuBnfxbpTKuMxyTg+eqcjusMYyqD+kLpElxyaUkAIxGWAsxomQq0Q5bKye1blc9TxXhTirbXG9H+fem6fguvmWJrU/ioCeKo2+I=
  skip_cleanup: true
  on:
    repo: dit4c/dit4c-helper-upload-webdav
