sudo: required
dist: trusty
language: generic
script: make && make test
after_success:
- make deploy
deploy:
- provider: releases
  api_key:
    secure: Eb+0GC0pGWQ4JfyMhJauLaoZ8Lycr9p95eRF9/JcBAXPn6Eo69JV+ybakRzKm1sGV9QpA+OzMFfNgRsY1zqGhgk8kBbAqT+Q+BxZDw+UGKKxA4Mgwv4Y/8O72pxcZqaIPkS8desYC0Z6bG1JYKdBIpIFZk9le9w7wIOt11xFmIljHWVe0qP4O6ksJSrhdOGxr1RTlty5Okhb8aqVgIQE7mc56npSl2CqRX7PmpADSLszSNZnXYIkTytY4n+70Nax9wPb/5xPULCwtSdJWFUxjah2aHa/W51mzT/KtHZvcfiKU4jmeybsijMRi3wrVOm1P/qbKE6XQPSLAEh+JFPdMfhG4qxObhbLTyHHJ9TDdT1ELf1g74dY+2VH+ZYm3wH0TLYNOTn/qql3y/798/+ZvhhavPvtx19gkk/HwHBgzp2PV3vfp0iQeScIszby0cXZzrieBypNERZrRI7VwTAng2gSYCrJUSDGm5IFablbRnxYz+w4Bw5DcbTYu3Z8+4cX1r57SLehRDDs7V/nu+f8l/3aSUEJgzCjLO2CxepEJBDr2gJTio43mjHjuXLp+mG3+TaSbP6RTkI72bOElaIjGw+jwceCy/A9vKlUc2gW7sH5+KuJzXfwscD5gLbTTCEHMpd3XcaofMm5Hh9fK2ntPvMd3+kcvfPvwSiQOT/8kkI=
  file:
  - dist/dit4c-helper-upload-webdav.linux.amd64.aci
  - dist/SHA512SUM
  skip_cleanup: true
  on:
    tags: true
    repo: dit4c/dit4c-helper-upload-webdav
- provider: bintray
  file: dist/bintray-descriptor.json
  user: tjdett
  key:
    secure: "XfCXO/dXMeOL/GSVucfXKJ5huH3ahNvEZHOaAB2wXxoxmX5UWX2f3GIYuGb7KEdL59Uuv8F1GUlU7pIGYBhKEWgAMDXoAK0kYfnmobOr5acLGCJUv/e2ifpV2zCsdGqe+u+4iNDWJ3Jt8ZKXqGN5Ja9ErxEpo/F7rMa1UWh/CBlXNTlZ9ed+PY4kWXTWvc79wzv8ICJGgbSuSf0xZPPqBvjIgabyzKwMwM+oC60xbVzyI+h9wJWXShWWi05shV+alPgZ4RXxdvm4WSqijLsqj6ZvliSakBitBtSbZVPJDh7RGjsKCobQJypYKwZqnCeN2nM3n/gYqrCIqxRWdZmkU9XuDVgZAI/gw9Ok3wnNM9gU0fI7KzbTqdbPAIgYENW7SNVt0MrIJFGWWRRJYTFF3+6+OndqZZI0z9MA4k0EYK5tv0VOp5ggTh01C2RhTpnJI0qrid4V6kj4IogDdeuIQbD5R1+3w1yu9cw6Jww1Nn4itxkTdzrS3V6mF9Wx2GPy5SFnIy1s3o/3vTvUv7gFiBc5TYC0Vg1W9pkn67X1T0U28DRmkQ1AymxjEQj8KGBGOcLVi5CPf2iEjH8PPxIQpmltx+JTh0zELTNDKEPRtY0HpenVu5Y4AW4TJ/gCBSNBYZ7GhHDGWA2ZOe/srBZ+qsH8xG47qDu/iZhBaPL/TbA="
  skip_cleanup: true
  on:
    tags: true
    repo: dit4c/dit4c-helper-upload-webdav
