sudo: required
dist: trusty
language: generic
script: make && make test
after_success:
- make deploy
deploy:
- provider: releases
  api_key:
    secure: Eb+0GC0pGWQ4JfyMhJauLaoZ8Lycr9p95eRF9/JcBAXPn6Eo69JV+ybakRzKm1sGV9QpA+OzMFfNgRsY1zqGhgk8kBbAqT+Q+BxZDw+UGKKxA4Mgwv4Y/8O72pxcZqaIPkS8desYC0Z6bG1JYKdBIpIFZk9le9w7wIOt11xFmIljHWVe0qP4O6ksJSrhdOGxr1RTlty5Okhb8aqVgIQE7mc56npSl2CqRX7PmpADSLszSNZnXYIkTytY4n+70Nax9wPb/5xPULCwtSdJWFUxjah2aHa/W51mzT/KtHZvcfiKU4jmeybsijMRi3wrVOm1P/qbKE6XQPSLAEh+JFPdMfhG4qxObhbLTyHHJ9TDdT1ELf1g74dY+2VH+ZYm3wH0TLYNOTn/qql3y/798/+ZvhhavPvtx19gkk/HwHBgzp2PV3vfp0iQeScIszby0cXZzrieBypNERZrRI7VwTAng2gSYCrJUSDGm5IFablbRnxYz+w4Bw5DcbTYu3Z8+4cX1r57SLehRDDs7V/nu+f8l/3aSUEJgzCjLO2CxepEJBDr2gJTio43mjHjuXLp+mG3+TaSbP6RTkI72bOElaIjGw+jwceCy/A9vKlUc2gW7sH5+KuJzXfwscD5gLbTTCEHMpd3XcaofMm5Hh9fK2ntPvMd3+kcvfPvwSiQOT/8kkI=
  file:
  - dist/dit4c-helper-upload-webdav.linux.amd64.aci
  - dist/SHA512SUM
  skip_cleanup: true
  on:
    tags: true
    repo: dit4c/dit4c-helper-upload-webdav
- provider: bintray
  file: dist/bintray-descriptor.json
  user: tjdett
  key:
    secure: W6jUp5dD3wdCgUDnj/ATcZuu/kKlu25pltP/G+JLPj5wbNMfESlsRPV0GwF6tSgcQt4dIlpub0xTcvrKaq1G6x4OI1reGu4UU1613EYIvySqFiduO/mbWETsHzSqW5xuc7k7ICQbEJnEvv7D2sCMwmzmLBcVwIgvlUdgOHhrtw/x9bg/E/p6OQdLbsiFz3DUn6nCrymjyBwcXxFH2VTPmAkmqFDB3VuyQXlm7gh6fZL5omsBRBRKjgaSx9grUf+Rh7oGkLuEHaS03sQG3o86RDJWz69EUTBqsCGq0AWMk7snantZ7ezgiUTWniFCZfsvH0lntXGsnuWmrwzu6iVkdvZAPnbLxK5+VjESiF4GVqdSjAO/ej7XqSx2OM1K88ct8zlp65SllP187Nmu7fds5hCxIjpm+7ccZM49FJQPG862AWYcbDhyJmRA//S2KZYCwREQGPs6lm0MnAe0cmfxtd+Y+FCjFC0pFPrRNKU+OJYDAGSH0iw2YV6Z+6xshqm9/eqBAr7zhH9mEHoY0Dn1J/9ca++spJeLq6K9WtRtAaPyBi9aBtRqg2KI9Nyj5NB1wabowqi93wLC1K9ttMGwlaH4cos6IknzjtGBM2DiBeGkfqYmS36JgAsl7ZkQnCXm2OdNVVDi5QomFWa+zfyFxHqGw/8gxAgg6jT6gCQVA6k=
  skip_cleanup: true
  on:
    repo: dit4c/dit4c-helper-upload-webdav
